spring:
  application:
    name: hr-worker
---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8888
---
spring:
  config:
    activate:
      on-profile: test
    import: optional:configserver:http://localhost:8888
---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://hr-config-server:8888