spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/workers/**
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/payments/**
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765

