spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Petraccino/ms-docker-configs
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888