spring:
  application:
    name: hr-config-server
  profiles:
    active: test
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Petraccino/ms-docker-configs
          username: ${GITHUB-USER}
          password: ${GITHUB-PASS}
management:
  endpoints:
    web:
    exposure:
      include: "*"
server:
  port: 8888