spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Petraccino/ms-docker-configs

server:
  port: 8888