create table worker (id int8 generated by default as identity, name varchar(255), daily_income int8 not null, primary key (id));

INSERT INTO worker (name, daily_Income) VALUES ('Bob', 200.0);
INSERT INTO worker (name, daily_Income) VALUES ('Maria', 300.0);
INSERT INTO worker (name, daily_Income) VALUES ('Alex', 250.0);